[tool.release_tool]
# Путь к каталогу с пакетами
packages_dir = "packages"

# Имя текстового файла, куда Stage 1 пишет список изменений (относительно каталога пакета)
changes_filename = "release_changes.txt"

# Имя текстового файла, в котором пользователь сохраняет сгенерированный LLM commit-message
commit_message_filename = "commit_message.txt"

# Файл-сообщение для тега
tag_message_filename = "tag_message.txt"

# Файлы с изменениями
changes_uncommitted_filename = "changes_uncommitted.txt"
changes_since_tag_filename = "changes_since_tag.txt"

# Каталог, куда складываются файлы изменений (будут созданы подкаталоги с именами пакетов)
changes_output_dir = "release_tool/changes"

# Префикс тега (например, v1.2.3)
tag_prefix = "v"

# Имя удалённого репозитория для push
git_remote = "origin"

# Сухой режим. Если true, скрипты только печатают действия, но не выполняют git-команды
dry_run = false